// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChunksColumns holds the columns for the "chunks" table.
	ChunksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "start", Type: field.TypeTime},
		{Name: "lease_expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"New", "Downloading", "Downloaded", "Processing", "Done"}, Default: "New"},
		{Name: "sha256_input", Type: field.TypeString, Nullable: true},
		{Name: "sha256_content", Type: field.TypeString, Nullable: true},
		{Name: "sha256_output", Type: field.TypeString, Nullable: true},
	}
	// ChunksTable holds the schema information for the "chunks" table.
	ChunksTable = &schema.Table{
		Name:       "chunks",
		Columns:    ChunksColumns,
		PrimaryKey: []*schema.Column{ChunksColumns[0]},
	}
	// WorkersColumns holds the columns for the "workers" table.
	WorkersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "token", Type: field.TypeString},
	}
	// WorkersTable holds the schema information for the "workers" table.
	WorkersTable = &schema.Table{
		Name:       "workers",
		Columns:    WorkersColumns,
		PrimaryKey: []*schema.Column{WorkersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChunksTable,
		WorkersTable,
	}
)

func init() {
}
