// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChunksColumns holds the columns for the "chunks" table.
	ChunksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "start", Type: field.TypeTime},
	}
	// ChunksTable holds the schema information for the "chunks" table.
	ChunksTable = &schema.Table{
		Name:       "chunks",
		Columns:    ChunksColumns,
		PrimaryKey: []*schema.Column{ChunksColumns[0]},
	}
	// DownloadsColumns holds the columns for the "downloads" table.
	DownloadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DownloadsTable holds the schema information for the "downloads" table.
	DownloadsTable = &schema.Table{
		Name:       "downloads",
		Columns:    DownloadsColumns,
		PrimaryKey: []*schema.Column{DownloadsColumns[0]},
	}
	// WorkersColumns holds the columns for the "workers" table.
	WorkersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "token", Type: field.TypeString},
	}
	// WorkersTable holds the schema information for the "workers" table.
	WorkersTable = &schema.Table{
		Name:       "workers",
		Columns:    WorkersColumns,
		PrimaryKey: []*schema.Column{WorkersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChunksTable,
		DownloadsTable,
		WorkersTable,
	}
)

func init() {
}
