// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/go-faster/gha/internal/ent/chunk"
	"github.com/go-faster/gha/internal/ent/download"
	"github.com/go-faster/gha/internal/ent/schema"
	"github.com/go-faster/gha/internal/ent/worker"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chunkMixin := schema.Chunk{}.Mixin()
	chunkMixinFields0 := chunkMixin[0].Fields()
	_ = chunkMixinFields0
	chunkFields := schema.Chunk{}.Fields()
	_ = chunkFields
	// chunkDescCreatedAt is the schema descriptor for created_at field.
	chunkDescCreatedAt := chunkMixinFields0[0].Descriptor()
	// chunk.DefaultCreatedAt holds the default value on creation for the created_at field.
	chunk.DefaultCreatedAt = chunkDescCreatedAt.Default.(func() time.Time)
	// chunkDescUpdatedAt is the schema descriptor for updated_at field.
	chunkDescUpdatedAt := chunkMixinFields0[1].Descriptor()
	// chunk.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chunk.DefaultUpdatedAt = chunkDescUpdatedAt.Default.(func() time.Time)
	// chunk.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chunk.UpdateDefaultUpdatedAt = chunkDescUpdatedAt.UpdateDefault.(func() time.Time)
	downloadMixin := schema.Download{}.Mixin()
	downloadMixinFields0 := downloadMixin[0].Fields()
	_ = downloadMixinFields0
	downloadMixinFields1 := downloadMixin[1].Fields()
	_ = downloadMixinFields1
	downloadFields := schema.Download{}.Fields()
	_ = downloadFields
	// downloadDescCreatedAt is the schema descriptor for created_at field.
	downloadDescCreatedAt := downloadMixinFields1[0].Descriptor()
	// download.DefaultCreatedAt holds the default value on creation for the created_at field.
	download.DefaultCreatedAt = downloadDescCreatedAt.Default.(func() time.Time)
	// downloadDescUpdatedAt is the schema descriptor for updated_at field.
	downloadDescUpdatedAt := downloadMixinFields1[1].Descriptor()
	// download.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	download.DefaultUpdatedAt = downloadDescUpdatedAt.Default.(func() time.Time)
	// download.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	download.UpdateDefaultUpdatedAt = downloadDescUpdatedAt.UpdateDefault.(func() time.Time)
	// downloadDescID is the schema descriptor for id field.
	downloadDescID := downloadMixinFields0[0].Descriptor()
	// download.DefaultID holds the default value on creation for the id field.
	download.DefaultID = downloadDescID.Default.(func() uuid.UUID)
	workerMixin := schema.Worker{}.Mixin()
	workerMixinFields0 := workerMixin[0].Fields()
	_ = workerMixinFields0
	workerMixinFields1 := workerMixin[1].Fields()
	_ = workerMixinFields1
	workerFields := schema.Worker{}.Fields()
	_ = workerFields
	// workerDescCreatedAt is the schema descriptor for created_at field.
	workerDescCreatedAt := workerMixinFields1[0].Descriptor()
	// worker.DefaultCreatedAt holds the default value on creation for the created_at field.
	worker.DefaultCreatedAt = workerDescCreatedAt.Default.(func() time.Time)
	// workerDescUpdatedAt is the schema descriptor for updated_at field.
	workerDescUpdatedAt := workerMixinFields1[1].Descriptor()
	// worker.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	worker.DefaultUpdatedAt = workerDescUpdatedAt.Default.(func() time.Time)
	// worker.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	worker.UpdateDefaultUpdatedAt = workerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workerDescID is the schema descriptor for id field.
	workerDescID := workerMixinFields0[0].Descriptor()
	// worker.DefaultID holds the default value on creation for the id field.
	worker.DefaultID = workerDescID.Default.(func() uuid.UUID)
}
