// Code generated by entc, DO NOT EDIT.

package worker

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the worker type in the database.
	Label = "worker"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// EdgeChunks holds the string denoting the chunks edge name in mutations.
	EdgeChunks = "chunks"
	// Table holds the table name of the worker in the database.
	Table = "workers"
	// ChunksTable is the table that holds the chunks relation/edge.
	ChunksTable = "chunks"
	// ChunksInverseTable is the table name for the Chunk entity.
	// It exists in this package in order to avoid circular dependency with the "chunk" package.
	ChunksInverseTable = "chunks"
	// ChunksColumn is the table column denoting the chunks relation/edge.
	ChunksColumn = "worker_chunks"
)

// Columns holds all SQL columns for worker fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldToken,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
